/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.salesController;
import lk.ijse.pos.modal.SalesReport;

/**
 *
 * @author ASUS
 */
public class BillPrint extends javax.swing.JFrame {

    /**
     * Creates new form BillPrint
     */
    public BillPrint() {
        try {
            initComponents();
            setValues();
            setTotal();
            setLocationRelativeTo(null);
         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFloor = new javax.swing.JLabel();
        lblTable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblOperator = new javax.swing.JLabel();
        lblFloorName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("resturant.UBR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, -1, -1));

        jLabel2.setText(".............................................................................................................");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, -1, -1));

        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));

        jLabel4.setText("Operator Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));
        jPanel1.add(lblFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 80, 20));
        jPanel1.add(lblTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, 20));

        jLabel7.setText(".............................................................................................................");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, 450, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Unit Price", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, 440, 229));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Thank You For Comming");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 480, -1, -1));

        jLabel9.setText(".............................................................................................................");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 416, 468, 11));

        jLabel10.setText(".............................................................................................................");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 452, 468, 10));

        lbltotal.setText("Total:");
        jPanel1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 434, -1, -1));

        lblDate.setText("Date:");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblOperator.setText("Operator Name:");
        jPanel1.add(lblOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 123, -1, -1));
        jPanel1.add(lblFloorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 100, -1, -1));

        jLabel13.setText("FloorName:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 100, -1, -1));

        jLabel14.setText("Table#");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 123, -1, -1));

        jLabel15.setText("Total:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 434, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFloor;
    private javax.swing.JLabel lblFloorName;
    private javax.swing.JLabel lblOperator;
    private javax.swing.JLabel lblTable;
    private javax.swing.JLabel lbltotal;
    // End of variables declaration//GEN-END:variables

    private void setValues() throws ClassNotFoundException, SQLException {
        

        OrderView orderView = new OrderView();
        String orderId = new OrderView().OrderId;
        List<SalesReport>list = new salesController().getSalesObj(orderId);
        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        for(SalesReport temp:list)
        {
            Object[] rowdata = {
                temp.getItem(),
                temp.getUnitPrice(),
                temp.getQty(),
                temp.getTotal()
                
                
            };
            modal.addRow(rowdata);
        }
        lblFloor.setText(OrderView.Floorname);
        lblOperator.setText(orderView.Employeeid);
        lblDate.setText(orderView.date+":"+OrderView.time);
        lblTable.setText(OrderView.TableID);
        
        
        
        



    }

    private void setTotal() {

        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        double total = 0;
        for(int i =0;i<modal.getRowCount();i++)
        {
            total+=Double.parseDouble (modal.getValueAt(i, 3).toString());
            
        }

        lbltotal.setText(String.valueOf(total));
    }
}
