/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.CustomerController;
import lk.ijse.pos.modal.Customer;
//import sun.security.pkcs11.Secmod;
//import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author ASUS
 */
public class CustomerView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        try {
            initComponents();
            loadToTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        cmbCustomerType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("CustomerPanel"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_customer_60px_1.png"))); // NOI18N
        jLabel1.setText("Manage Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 330, 70));

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 410, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Customer Type");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Customer Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 30));

        txtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIDActionPerformed(evt);
            }
        });
        add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 410, 30));

        cmbCustomerType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCustomerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Foreign" }));
        add(cmbCustomerType, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 420, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Customer Id");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", " Name", "Type"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 1180, 470));

        btnAdd.setBackground(new java.awt.Color(0, 0, 204));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 130, 50));

        btnDelete.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 740, 130, 50));

        btnDelete1.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 740, 130, 50));

        btnEdit1.setBackground(new java.awt.Color(0, 204, 0));
        btnEdit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 740, 130, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed

        if(txtCustomerID.getText().trim().length()>0)
        {
            try {
                Customer obj = new CustomerController().getCustomerObj(txtCustomerID.getText().trim());
                if(obj != null)
                {
                    txtCustomerName.setText(obj.getName());
                    cmbCustomerType.setSelectedItem(obj.getType());
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "please insert id","Error",JOptionPane.ERROR_MESSAGE);
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        
        String id = txtCustomerID.getText();
        String name = txtCustomerName.getText();
        String type = cmbCustomerType.getSelectedItem().toString();
        Customer obj = new Customer(id, name, type);
        if(txtCustomerID.getText().trim().length()>0)
        {
            try {
                boolean isSave= new CustomerController().saveCustomer(obj);
               
                if(isSave)
                {
                    JOptionPane.showMessageDialog(this, "Saved");
                    loadToTable();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "please Insert an Id","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btnAddActionPerformed
 
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(txtCustomerID.getText().trim().length()>0)
        {
            try {
                boolean isdelete = new CustomerController().deleteCustomer(txtCustomerID.getText().trim());
                if(isdelete)
                {
                    JOptionPane.showMessageDialog(this, "Deleted");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Insert Id","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked

        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();
        int row = tbl.getSelectedRow();
        txtCustomerID.setText(modal.getValueAt(row, 0).toString());
        txtCustomerName.setText(modal.getValueAt(row, 1).toString());
        cmbCustomerType.setSelectedItem(modal.getValueAt(row, 2).toString());



    }//GEN-LAST:event_tblMouseClicked

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        if(txtCustomerID.getText().trim().length()>0)
        {
             
            try {
                String id = txtCustomerID.getText();
                String name = txtCustomerName.getText();
                String type = cmbCustomerType.getSelectedItem().toString();
                Customer obj = new Customer(id, name, type);
                boolean isupdate = new CustomerController().updateCustomer(obj);
                if(isupdate)
                {
                    JOptionPane.showMessageDialog(this,"Updated.....");
                    loadToTable();
                }
                else
                {
                     JOptionPane.showMessageDialog(this, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "please Insert an Id ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JComboBox<String> cmbCustomerType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables

    private void loadToTable() throws ClassNotFoundException, SQLException {

        DefaultTableModel modal =(DefaultTableModel) tbl.getModel();
        modal.setRowCount(0);
        
        List<Customer>customerlist = new CustomerController().getCustomerList();
        for(Customer temp: customerlist)
        {
            modal.addRow(new Object[]{
                temp.getCustomerID(),
                temp.getName(),
                temp.getType()
                
            });
        }

    }
}
