/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.LabourController;
import lk.ijse.pos.modal.Labour;

/**
 *
 * @author ASUS
 */
public class LabourView extends javax.swing.JPanel {

    /**
     * Creates new form LabourView
     */
    public LabourView() {
        try {
            initComponents();
            getSelectedRadioButton();
            getLabourListtoTable();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtTp = new javax.swing.JTextField();
        txtLabourID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radioMale = new javax.swing.JRadioButton();
        radioOther = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        btnDelete1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnTableAdd = new javax.swing.JButton();
        btncleartext = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_worker_48px_2.png"))); // NOI18N
        jLabel1.setText(" Manage Labour ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 330, 70));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tp");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 40, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 360, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Labour_Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Name");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Sex");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 40, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Nic");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 40, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Adress");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, 30));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 360, 30));

        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 550, 30));

        txtTp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTpActionPerformed(evt);
            }
        });
        add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 550, 30));

        txtLabourID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabourIDActionPerformed(evt);
            }
        });
        add(txtLabourID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 360, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LabourId", "Name", "Sex", "Nic", "Adress", "Tp"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1200, 430));

        radioMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        radioOther.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioOther.setText("Other");
        radioOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOtherActionPerformed(evt);
            }
        });
        add(radioOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

        radioFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioFemale.setText("Female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        btnDelete1.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 740, 130, 50));

        btnEdit1.setBackground(new java.awt.Color(0, 153, 0));
        btnEdit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 130, 50));

        btnTableAdd.setBackground(new java.awt.Color(0, 0, 204));
        btnTableAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTableAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnTableAdd.setText("Add");
        btnTableAdd.setBorder(null);
        btnTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableAddActionPerformed(evt);
            }
        });
        add(btnTableAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 130, 50));

        btncleartext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncleartext.setText("Clear Text");
        btncleartext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleartextActionPerformed(evt);
            }
        });
        add(btncleartext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtTpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTpActionPerformed

    private void txtLabourIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabourIDActionPerformed

        if(txtLabourID.getText().trim().length()>0)
        {
            try {
                Labour obj = new LabourController().getLabourObj(txtLabourID.getText().trim());
                if(obj != null)
                {
                    txtLabourID.setText(obj.getEmpId());
                    txtName.setText(obj.getName());
                    txtAddress.setText(obj.getAdress());
                    txtNic.setText(obj.getNic());
                    txtTp.setText(obj.getTp());
                    String sex = obj.getSex(); 
                    if(sex.equals("Male"))
                    {
                     radioMale.setSelected(true);
                     radioFemale.setSelected(false);
                     radioOther.setSelected(false);
                    }
                    else if(sex.equals("Female"))
                    {
                     radioFemale.setSelected(true);
                     radioMale.setSelected(false);
                     radioOther.setSelected(false);
                    }
                    else
                    {
                     radioOther.setSelected(true);
                     radioMale.setSelected(false);
                     radioFemale.setSelected(false);
                    }
                    
                   
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Insert An Id","Error",JOptionPane.ERROR_MESSAGE);
        }
        
          
    }//GEN-LAST:event_txtLabourIDActionPerformed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed

        if(radioMale.isSelected())
        {
            radioFemale.setSelected(false);
            radioOther.setSelected(false);
        }

    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOtherActionPerformed

        if(radioOther.isSelected())
        {
            radioMale.setSelected(false);
            radioFemale.setSelected(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_radioOtherActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed

       if(radioFemale.isSelected())
       {
           radioMale.setSelected(false);
           radioOther.setSelected(false);
       }
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        int row =jTable1.getSelectedRow();
        txtLabourID.setText(modal.getValueAt(row, 0).toString());
        txtName.setText(modal.getValueAt(row, 1).toString());
        txtAddress.setText(modal.getValueAt(row, 4).toString());
        txtNic.setText(modal.getValueAt(row, 3).toString());
        txtTp.setText(modal.getValueAt(row, 5).toString());
        String sex = modal.getValueAt(row, 2).toString();
        if(sex.equals("Male"))
        {
            radioMale.setSelected(true);
            radioFemale.setSelected(false);
            radioOther.setSelected(false);
        }
        else if(sex.equals("Female"))
        {
            radioFemale.setSelected(true);
             radioMale.setSelected(false);
            radioOther.setSelected(false);
        }
        else
        {
            radioOther.setSelected(true);
             radioMale.setSelected(false);
            radioFemale.setSelected(false);
        }
                


        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed

        if(txtLabourID.getText().trim().length()>0)
        {
            try {
                boolean isDelete = new LabourController().deleteLabour(txtLabourID.getText().trim());
                
                
                if(isDelete)
                {
                   JOptionPane.showMessageDialog(this, "Deleted..");
                    getLabourListtoTable();
                }
            
                else
                {
                    JOptionPane.showMessageDialog(null,"Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }  
                
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Try Again","Warning",JOptionPane.WARNING_MESSAGE);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed

      if(txtLabourID.getText().trim().length()>0)
        {
            try {
                String id = txtLabourID.getText();
                String name = txtName.getText();
                String Sex = getSelectedRadioButton();
                String nic = txtNic.getText();
                String adress = txtAddress.getText();
                String tp =txtTp.getText();
                
                Labour obj = new Labour(id, name, Sex, nic, adress, tp);
                
                
                boolean isUpdate = new LabourController().updateLabour(obj);
                
                if(isUpdate)
                {
                    JOptionPane.showMessageDialog(this, "Updated..");
                    getLabourListtoTable();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Insert An Id...","Error",JOptionPane.ERROR_MESSAGE);
        }
        




    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableAddActionPerformed

        
        String id = txtLabourID.getText();
        String name = txtName.getText();
        String Sex = getSelectedRadioButton();
        String nic = txtNic.getText();
        String adress = txtAddress.getText();
        String tp =txtTp.getText();
        Labour obj = new Labour(id, name, Sex, nic, adress, tp);
        try {
            if(txtLabourID.getText().trim().length()>0)
            {
            boolean isSaved = new LabourController().saveLabour(obj);
            if(isSaved)
            {
                JOptionPane.showMessageDialog(this, "Saved");
                getLabourListtoTable();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
            }
            
            
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Please Insert An Id...","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LabourView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTableAddActionPerformed

    private void btncleartextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleartextActionPerformed
        txtAddress.setText("");
        txtLabourID.setText("");
        txtName.setText("");
        txtNic.setText("");
        txtTp.setText("");
        radioFemale.setSelected(false);
        radioMale.setSelected(false);
        radioOther.setSelected(false);

    }//GEN-LAST:event_btncleartextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnTableAdd;
    private javax.swing.JButton btncleartext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioOther;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtLabourID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtTp;
    // End of variables declaration//GEN-END:variables

    private String getSelectedRadioButton() {
       
        if(radioMale.isSelected())
        {
            return "Male";
        }
        else if(radioFemale.isSelected())
        {
            return "Female";
        }
        else
        {
          return "Other";
        
        }
    }

    private void getLabourListtoTable() throws ClassNotFoundException, SQLException {

        DefaultTableModel modal = (DefaultTableModel) jTable1.getModel();
        modal.setRowCount(0);
        List<Labour>list  = new LabourController().getLabourList();

        for(Labour tempList : list)
        {
          modal.addRow(new Object[]{
              tempList.getEmpId(),
              tempList.getName(),
              tempList.getSex(),
              tempList.getNic(),
              tempList.getAdress(),
              tempList.getTp()
              
          });
              
          
                  
                  
                  
        }
        


    }
    
}
