/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.pos.controller.CatagoryController;
import lk.ijse.pos.controller.CustomerController;
import lk.ijse.pos.controller.ItemController;
import lk.ijse.pos.controller.TableController;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            getTotalItemCount();
            getTotalCatagoryCount();
            getTotalTableCount();
            getTotalCustomer();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClient = new javax.swing.JButton();
        ITEM = new javax.swing.JButton();
        btnplaceorder = new javax.swing.JButton();
        Table = new javax.swing.JButton();
        btnLabour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnItem = new javax.swing.JButton();
        btnSalesReport = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        paneltotalCatagory = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbltotalcatagory = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelTotalItems2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbltotaltables = new javax.swing.JLabel();
        panelTotalItems3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbltotalclients = new javax.swing.JLabel();
        panelTotalItems1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbltotalitems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(170, 0, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Contact");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 740, 83, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Log out");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 83, -1));

        btnClient.setBackground(new java.awt.Color(170, 0, 255));
        btnClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClient.setForeground(new java.awt.Color(255, 255, 255));
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_customer_60px_1.png"))); // NOI18N
        btnClient.setText("CLIENT              ");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 80));

        ITEM.setBackground(new java.awt.Color(170, 0, 255));
        ITEM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ITEM.setForeground(new java.awt.Color(255, 255, 255));
        ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_food_50px_1.png"))); // NOI18N
        ITEM.setText("CATAGORY        ");
        ITEM.setMaximumSize(new java.awt.Dimension(131, 31));
        ITEM.setPreferredSize(new java.awt.Dimension(131, 31));
        ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMActionPerformed(evt);
            }
        });
        jPanel1.add(ITEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300, 80));

        btnplaceorder.setBackground(new java.awt.Color(170, 0, 255));
        btnplaceorder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnplaceorder.setForeground(new java.awt.Color(255, 255, 255));
        btnplaceorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_add_shopping_cart_50px.png"))); // NOI18N
        btnplaceorder.setText("PLACE ORDER  ");
        btnplaceorder.setMaximumSize(new java.awt.Dimension(131, 31));
        btnplaceorder.setPreferredSize(new java.awt.Dimension(131, 31));
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnplaceorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 300, 80));

        Table.setBackground(new java.awt.Color(170, 0, 255));
        Table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_wooden_massage_table_40px_1.png"))); // NOI18N
        Table.setText("TABLE & FLOOR");
        Table.setActionCommand("TABLE  &\nFLOOR");
        Table.setMaximumSize(new java.awt.Dimension(131, 31));
        Table.setPreferredSize(new java.awt.Dimension(131, 31));
        Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableActionPerformed(evt);
            }
        });
        jPanel1.add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 80));

        btnLabour.setBackground(new java.awt.Color(170, 0, 255));
        btnLabour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLabour.setForeground(new java.awt.Color(255, 255, 255));
        btnLabour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_worker_48px_2.png"))); // NOI18N
        btnLabour.setText("LABOUR            ");
        btnLabour.setMaximumSize(new java.awt.Dimension(131, 31));
        btnLabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabourActionPerformed(evt);
            }
        });
        jPanel1.add(btnLabour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 300, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_details_40px_4.png"))); // NOI18N
        jLabel2.setText("Dashbord");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnItem.setBackground(new java.awt.Color(170, 0, 255));
        btnItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnItem.setForeground(new java.awt.Color(255, 255, 255));
        btnItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_kawaii_pizza_40px.png"))); // NOI18N
        btnItem.setText("ITEM                  ");
        btnItem.setMaximumSize(new java.awt.Dimension(131, 31));
        btnItem.setPreferredSize(new java.awt.Dimension(131, 31));
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 80));

        btnSalesReport.setBackground(new java.awt.Color(170, 0, 255));
        btnSalesReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_analyze_40px_4.png"))); // NOI18N
        btnSalesReport.setText("SALES  REPORT");
        btnSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalesReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 300, 80));

        btnHome.setBackground(new java.awt.Color(170, 0, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_home_page_50px_2.png"))); // NOI18N
        btnHome.setText("HOME                 ");
        btnHome.setMaximumSize(new java.awt.Dimension(131, 31));
        btnHome.setPreferredSize(new java.awt.Dimension(131, 31));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 80));

        btnHome2.setBackground(new java.awt.Color(170, 0, 255));
        btnHome2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome2.setForeground(new java.awt.Color(255, 255, 255));
        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_home_page_50px_2.png"))); // NOI18N
        btnHome2.setText("HOME                 ");
        btnHome2.setMaximumSize(new java.awt.Dimension(131, 31));
        btnHome2.setPreferredSize(new java.awt.Dimension(131, 31));
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 80));

        btnHome3.setBackground(new java.awt.Color(170, 0, 255));
        btnHome3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome3.setForeground(new java.awt.Color(255, 255, 255));
        btnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_home_page_50px_2.png"))); // NOI18N
        btnHome3.setText("HOME                 ");
        btnHome3.setMaximumSize(new java.awt.Dimension(131, 31));
        btnHome3.setPreferredSize(new java.awt.Dimension(131, 31));
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 800));

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));
        jPanel4.setForeground(new java.awt.Color(0, 0, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 0, -1, -1));

        MainPanal.setBackground(new java.awt.Color(255, 255, 255));
        MainPanal.setPreferredSize(new java.awt.Dimension(1250, 800));
        MainPanal.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/icon/icons8_palm_tree_48px_1.png"))); // NOI18N
        jLabel1.setText("Clamender Unawatuna Beach Resort");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorRemoved(evt);
            }
        });
        MainPanal.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        paneltotalCatagory.setBackground(new java.awt.Color(211, 84, 0));

        jPanel6.setBackground(new java.awt.Color(170, 0, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total CATAGORY");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbltotalcatagory.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltotalcatagory.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalcatagory.setText("x");

        javax.swing.GroupLayout paneltotalCatagoryLayout = new javax.swing.GroupLayout(paneltotalCatagory);
        paneltotalCatagory.setLayout(paneltotalCatagoryLayout);
        paneltotalCatagoryLayout.setHorizontalGroup(
            paneltotalCatagoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltotalCatagoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalcatagory)
                .addGap(121, 121, 121))
        );
        paneltotalCatagoryLayout.setVerticalGroup(
            paneltotalCatagoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltotalCatagoryLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbltotalcatagory)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTotalItems2.setBackground(new java.awt.Color(52, 152, 219));

        jPanel9.setBackground(new java.awt.Color(170, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total TABLES");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(62, 62, 62))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbltotaltables.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltotaltables.setForeground(new java.awt.Color(255, 255, 255));
        lbltotaltables.setText("x");

        javax.swing.GroupLayout panelTotalItems2Layout = new javax.swing.GroupLayout(panelTotalItems2);
        panelTotalItems2.setLayout(panelTotalItems2Layout);
        panelTotalItems2Layout.setHorizontalGroup(
            panelTotalItems2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalItems2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotaltables)
                .addGap(128, 128, 128))
        );
        panelTotalItems2Layout.setVerticalGroup(
            panelTotalItems2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalItems2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbltotaltables)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        panelTotalItems3.setBackground(new java.awt.Color(0, 204, 102));

        jPanel10.setBackground(new java.awt.Color(170, 0, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total CLIENTS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(62, 62, 62))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbltotalclients.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltotalclients.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalclients.setText("x");

        javax.swing.GroupLayout panelTotalItems3Layout = new javax.swing.GroupLayout(panelTotalItems3);
        panelTotalItems3.setLayout(panelTotalItems3Layout);
        panelTotalItems3Layout.setHorizontalGroup(
            panelTotalItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalItems3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalclients)
                .addGap(128, 128, 128))
        );
        panelTotalItems3Layout.setVerticalGroup(
            panelTotalItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalItems3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbltotalclients)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        panelTotalItems1.setBackground(new java.awt.Color(230, 126, 34));

        jPanel8.setBackground(new java.awt.Color(170, 0, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total ITEMS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(62, 62, 62))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbltotalitems.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltotalitems.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalitems.setText("x");

        javax.swing.GroupLayout panelTotalItems1Layout = new javax.swing.GroupLayout(panelTotalItems1);
        panelTotalItems1.setLayout(panelTotalItems1Layout);
        panelTotalItems1Layout.setHorizontalGroup(
            panelTotalItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalItems1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalitems)
                .addGap(128, 128, 128))
        );
        panelTotalItems1Layout.setVerticalGroup(
            panelTotalItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalItems1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbltotalitems)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panelTotalItems1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250)
                                .addComponent(paneltotalCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panelTotalItems2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250)
                                .addComponent(panelTotalItems3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(208, 208, 208))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalItems1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneltotalCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalItems3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTotalItems2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MainPanal.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(MainPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1250, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabourActionPerformed
         LabourView labour = new LabourView();
         MainPanal.removeAll();
         MainPanal.revalidate();
         MainPanal.repaint();
         
         MainPanal.add(labour);
         MainPanal.revalidate();
         MainPanal.repaint();
        

    }//GEN-LAST:event_btnLabourActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
            

        CustomerView customer = new CustomerView();
        MainPanal.removeAll();
         MainPanal.revalidate();
         MainPanal.repaint();
         
         MainPanal.add(customer);
         MainPanal.revalidate();
         MainPanal.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientActionPerformed

    private void ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMActionPerformed

        CatagaryView cview = new CatagaryView();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        
        MainPanal.add(cview);
        MainPanal.revalidate();
        MainPanal.repaint();


        
    }//GEN-LAST:event_ITEMActionPerformed

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed

        
        OrderView order = new OrderView();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        MainPanal.add(order);
        MainPanal.revalidate();
        MainPanal.repaint();
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnplaceorderActionPerformed

    private void TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableActionPerformed
       
        TableView table = new TableView();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        
        MainPanal.add(table);
        MainPanal.revalidate();
        MainPanal.repaint();


    }//GEN-LAST:event_TableActionPerformed

    private void jLabel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorRemoved

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        dispose();
        LoginView login = new LoginView();
        login.setVisible(true);

        
        




        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed

        ItemView item = new ItemView();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        
        MainPanal.add(item);
        MainPanal.revalidate();
        MainPanal.repaint();





       
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesReportActionPerformed

        SalesView sales = new SalesView();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        
        MainPanal.add(sales);
        MainPanal.revalidate();
        MainPanal.repaint();



        
    }//GEN-LAST:event_btnSalesReportActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
 
        Main main = new Main();
        MainPanal.removeAll();
        MainPanal.revalidate();
        MainPanal.repaint();
        
        MainPanal.add(main.MainPanal);
        MainPanal.revalidate();
        MainPanal.repaint();
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
      
    }//GEN-LAST:event_btnHome3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ITEM;
    private javax.swing.JPanel MainPanal;
    private javax.swing.JButton Table;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnLabour;
    private javax.swing.JButton btnSalesReport;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbltotalcatagory;
    private javax.swing.JLabel lbltotalclients;
    private javax.swing.JLabel lbltotalitems;
    private javax.swing.JLabel lbltotaltables;
    private javax.swing.JPanel panelTotalItems1;
    private javax.swing.JPanel panelTotalItems2;
    private javax.swing.JPanel panelTotalItems3;
    private javax.swing.JPanel paneltotalCatagory;
    // End of variables declaration//GEN-END:variables

   
    private void getTotalItemCount() throws ClassNotFoundException, SQLException {

        int itemcount= new ItemController().getItemCount();
        
        lbltotalitems.setText(String.valueOf(itemcount));


    }

    private void getTotalCatagoryCount() throws ClassNotFoundException, SQLException {

        int catagoryCount = new CatagoryController().getCatagoryCount();
        lbltotalcatagory.setText(String.valueOf(catagoryCount));

    }

    private void getTotalTableCount() throws ClassNotFoundException, SQLException {

        int tablecount = new TableController().getTableCount();
        lbltotaltables.setText(String.valueOf(tablecount ));
    }

    private void getTotalCustomer() throws ClassNotFoundException, SQLException {

        int customerCount = new CustomerController().getCustomerCount();
        lbltotalclients.setText(String.valueOf(customerCount));
        

    }



    }

   
   





