/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import lk.ijse.pos.controller.Dbcontroller;
import lk.ijse.pos.controller.salesController;
import lk.ijse.pos.modal.SalesReport;
//import org.apache.commons.dbutils.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import sun.security.pkcs11.Secmod;
//import net.proteanit.sql.DbUtils;
//import org.apache.commons.dbutils.DbUtils;

/**
 *
 * @author ASUS
 */
public class SalesView extends javax.swing.JPanel {

    /**
     * Creates new form SalesView
     */
    public SalesView() {
        try {
            initComponents();
            insertToTalbe();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SalesView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SalesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    ArrayList<String>list;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "CustomerName", "OrderID", "Item", "Catagory", "Qty", "price", "OrderType", "Payment_Methord", "Date", "Time", "FloorNo", "TableID", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbl.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1250, 700));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Sales Report");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 330, 70));

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });
        add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased

        DefaultTableModel modal = (DefaultTableModel) tbl.getModel();
        
        try {
            String text = txtFilter.getText();
             ResultSet set= new salesController().getSearchdata(text);
             Connection con = Dbcontroller.getInstance().getConnection();
            
            tbl.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(set));
            
            
          
            
            
                   
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SalesView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SalesView.class.getName()).log(Level.SEVERE, null, ex);
        }
     
       
        
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    private void insertToTalbe() throws ClassNotFoundException, SQLException {

        DefaultTableModel modal =(DefaultTableModel) tbl.getModel();
        List<SalesReport>list = new salesController().getSalesList();
        for(SalesReport temp:list)
        {
            Object [] rowdata = {
                temp.getSid(),
                temp.getCustomername(),
                temp.getOrderID(),
                temp.getItem(),
                temp.getCatagory(),
                temp.getQty(),
                temp.getUnitPrice(),
                temp.getOrdertype(),
                temp.getPaymentMethord(),
                temp.getDate(),
                temp.getTime(),
                temp.getFloorName(),
                temp.getTableName(),
                temp.getTotal()
            };
            modal.addRow(rowdata);
                    
        }
        
        

    }

  
        

    

    private void filter(String query) {

       
    }
}
