/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.sql.SQLException;
//import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.FloorController;
import lk.ijse.pos.controller.TableController;
import lk.ijse.pos.modal.Floor;
import lk.ijse.pos.modal.Table;
//import sun.java2d.pipe.SpanShapeRenderer;
//import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author ASUS
 */
public class TableView extends javax.swing.JPanel {

    /**
     * Creates new form AllView
     */
    public TableView() {
        try {
            initComponents();
            setDate();
            setToTableFloor();
            AddFloorNameList();
            setToTabletables();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTableNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtChair = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbFloor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTableId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTableAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFloorId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFloorName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFloor = new javax.swing.JTable();
        btnDeleteFloor = new javax.swing.JButton();
        btnEditFloor = new javax.swing.JButton();
        btnFloorAdd = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1250, 800));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Table No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 30));

        txtTableNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTableNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTableNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 470, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Floor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 80, 30));

        txtChair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChairActionPerformed(evt);
            }
        });
        jPanel1.add(txtChair, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 440, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Table ID ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, 30));

        cmbFloor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFloorItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 440, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Chairs");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 80, 30));

        txtTableId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTableIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtTableId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 470, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TableId", "TableNo", "FloorID", "Chairs"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1140, 540));

        btnEdit.setBackground(new java.awt.Color(0, 204, 0));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 130, 50));

        btnDelete.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 130, 50));

        btnTableAdd.setBackground(new java.awt.Color(0, 0, 204));
        btnTableAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTableAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnTableAdd.setText("Add");
        btnTableAdd.setBorder(null);
        btnTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnTableAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 130, 50));

        jTabbedPane1.addTab("TABLE", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1250, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Entry Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Floor Id");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 30));

        txtFloorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFloorIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtFloorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 470, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Floor No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 30));

        txtFloorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFloorNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFloorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 470, 30));

        tblFloor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Floor Id", "Floor No", "Entry Date"
            }
        ));
        tblFloor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFloorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFloor);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 1080, 420));

        btnDeleteFloor.setBackground(new java.awt.Color(153, 0, 0));
        btnDeleteFloor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteFloor.setForeground(new java.awt.Color(0, 0, 204));
        btnDeleteFloor.setText("Delete");
        btnDeleteFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFloorActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 130, 50));

        btnEditFloor.setBackground(new java.awt.Color(0, 153, 0));
        btnEditFloor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditFloor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditFloor.setText("Edit");
        btnEditFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFloorActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 130, 50));

        btnFloorAdd.setBackground(new java.awt.Color(0, 0, 204));
        btnFloorAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFloorAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnFloorAdd.setText("Add");
        btnFloorAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloorAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnFloorAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 130, 50));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 370, 30));

        jTabbedPane1.addTab("FLOOR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTableNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTableNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTableNoActionPerformed

    private void txtChairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChairActionPerformed

    private void txtTableIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTableIdActionPerformed

        if(txtTableId.getText().trim().length()>0)
        {
            try {
                Table obj = new TableController().getTableObj(txtTableId.getText().trim());
                if(obj != null)
                {
                     txtTableId.setText(obj.getTableID());
                     txtTableNo.setText(obj.getTableNo());
                     txtChair.setText(String.valueOf(obj.getChairs()));
                     String FloorId = obj.getFloorId();
                     String floorname = new FloorController().getFloorName(FloorId);
                     cmbFloor.setSelectedItem(floorname);
                } 
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Insert Id","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_txtTableIdActionPerformed

    private void txtFloorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFloorIdActionPerformed
        // TODO add your handling code he
        
        
        
        
        if(txtFloorId.getText().trim().length()>0)
        {
            try {
                Floor obj = new FloorController().getFloorObj(txtFloorId.getText().trim());
                
                if(obj != null)
                {
                    txtFloorName.setText(obj.getName());
                    //TxtEntryDate.setText(obj.getEntry_Date());
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Try again..","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Insert An Id","Error",JOptionPane.ERROR_MESSAGE);
        }


        
    }//GEN-LAST:event_txtFloorIdActionPerformed

    private void txtFloorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFloorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFloorNameActionPerformed

    private void btnFloorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloorAddActionPerformed
      String id= txtFloorId.getText();
      String name =txtFloorName.getText();
      
      SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
      String date = format.format(jDateChooser1.getDate());
      
      Floor obj = new Floor(id, name, date);
      
      if(txtFloorId.getText().length()>0)
      {
          try {
              boolean isSaved = new FloorController().savedFloor(obj);
              
              
              
              if(isSaved)
              {
                  JOptionPane.showMessageDialog(this, "Saved..");
                  setToTableFloor();
                  
              }
              else
              {
                  JOptionPane.showMessageDialog(null,"Tryagain","Warning",JOptionPane.WARNING_MESSAGE );
              }
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      else 
      {
          JOptionPane.showMessageDialog(this, "Please Insert Id ","Error",JOptionPane.ERROR_MESSAGE);
      }
      
        


    }//GEN-LAST:event_btnFloorAddActionPerformed

    private void btnEditFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFloorActionPerformed

        try {
            String id= txtFloorId.getText();
            String name = txtFloorName.getText();
            SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
            String date = format.format(jDateChooser1.getDate());
            
            
            
            
            Floor floor = new Floor(id, name, date);
            boolean isUpdated = new FloorController().updateFloor(floor);
            
            if(isUpdated)
            {
            JOptionPane.showMessageDialog(this, "Updated..");
            setToTableFloor();
            
            }
              else
              {
                  JOptionPane.showMessageDialog(null,"Tryagain","Warning",JOptionPane.WARNING_MESSAGE );
              }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
    }//GEN-LAST:event_btnEditFloorActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked

        try {
            DefaultTableModel modal = (DefaultTableModel) tbl.getModel();
            int row = tbl.getSelectedRow();
            String floorid = modal.getValueAt(row, 2).toString();
            String floorname = FloorController.getFloorname(floorid);
            
            txtTableId.setText(modal.getValueAt(row, 0).toString());
            txtTableNo.setText(modal.getValueAt(row, 1).toString());
            cmbFloor.setSelectedItem(floorname);
            txtChair.setText(modal.getValueAt(row, 3).toString());
            
            
            
            
            
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void tblFloorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFloorMouseClicked

         DefaultTableModel modal = (DefaultTableModel) tblFloor.getModel();
        int row = tblFloor.getSelectedRow();
            
        txtFloorId.setText(modal.getValueAt(row,0).toString());
        txtFloorName.setText(modal.getValueAt(row, 1).toString());
        try {
            String dt = modal.getValueAt(row, 2).toString();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dt);
            jDateChooser1.setDate(date);
            
            
            
            
            
            // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblFloorMouseClicked

    private void btnDeleteFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFloorActionPerformed

        if(txtFloorId.getText().trim().length()>0)
        {
            try {
                boolean isDeleted = new FloorController().DeleteFloor(txtFloorId.getText().trim());
                
             if(isDeleted)
            {
            JOptionPane.showMessageDialog(this, "Deleted..");
            setToTableFloor();
            }
              else
              {
                  JOptionPane.showMessageDialog(null,"Tryagain","Warning",JOptionPane.WARNING_MESSAGE );
              }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Insert Id..","Error",JOptionPane.ERROR_MESSAGE);
        }
      



        
    }//GEN-LAST:event_btnDeleteFloorActionPerformed

    private void btnTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableAddActionPerformed

        if(txtTableId.getText().trim().length()>0)
        {
            try {
                String id = txtTableId.getText();
                String name = txtTableNo.getText();
                int chair = Integer.parseInt(txtChair.getText());
                
                Table obj= new Table(id, floorId, name, chair);
                
                
                boolean isSaved = new TableController().saveTables(obj);
                if(isSaved)
                {
                    JOptionPane.showMessageDialog(this, "Saved");
                    setToTabletables();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Tryagain","Warning",JOptionPane.WARNING_MESSAGE );
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Please Insert Id..","Error",JOptionPane.ERROR_MESSAGE);
        }



        
    }//GEN-LAST:event_btnTableAddActionPerformed

    private void cmbFloorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFloorItemStateChanged

        try {
             floorId = new FloorController().getFloorId(cmbFloor.getSelectedItem().toString());
            
            System.out.println(floorId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }


     
    }//GEN-LAST:event_cmbFloorItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            String id = txtTableId.getText();
            String name = txtTableNo.getText();
            int chair = Integer.parseInt(txtChair.getText());
            
            Table obj = new Table(id, floorId, name, chair);
            boolean isUpdated = new TableController().UpdateTable(obj);
            if(isUpdated)
            {
                JOptionPane.showMessageDialog(this, "Updated....");
                setToTabletables();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Try Again...");
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
       


      
    }//GEN-LAST:event_btnEditActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        


    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(txtTableId.getText().trim().length()>0)
        {
            try {
                boolean isDeleted = new TableController().DeleteTable(txtTableId.getText().trim());
                if(isDeleted)
                {
                    JOptionPane.showMessageDialog(this, "Deleted");
                    setToTabletables();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Try Again","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"please Insert An Id","Error",JOptionPane.ERROR_MESSAGE);
        }
       




        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

   
    
    String floorId;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteFloor;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditFloor;
    private javax.swing.JButton btnFloorAdd;
    private javax.swing.JButton btnTableAdd;
    private javax.swing.JComboBox<String> cmbFloor;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tblFloor;
    private javax.swing.JTextField txtChair;
    private javax.swing.JTextField txtFloorId;
    private javax.swing.JTextField txtFloorName;
    private javax.swing.JTextField txtTableId;
    private javax.swing.JTextField txtTableNo;
    // End of variables declaration//GEN-END:variables

    private void setDate() {


        Date date = new Date();
        SimpleDateFormat format= new SimpleDateFormat("YYYY-MM-dd");
       

    }

    private void setToTableFloor() throws ClassNotFoundException, SQLException {

        DefaultTableModel modal = (DefaultTableModel) tblFloor.getModel();
        modal.setRowCount(0);
        List<Floor>floorList = new FloorController().getFloorList();
        
        for(Floor templist:floorList)
        {
            modal.addRow(new Object[]{
                
                templist.getFloorId(),
                templist.getName(),
                templist.getEntry_Date()
            });
        }
        


    }

    private void AddFloorNameList() throws ClassNotFoundException, SQLException {
       
        List<String>FloorName = new FloorController().getFloorNameList();
        for(String templist:FloorName)
        {
            cmbFloor.addItem(templist);
        }
        
        
        
    }

    private void setToTabletables() throws ClassNotFoundException, SQLException {

        DefaultTableModel modal =(DefaultTableModel) tbl.getModel(); 
        modal.setRowCount(0);
        List<Table> tablelist = new TableController().getTablelist();
        for(Table temp:tablelist)
        {
            modal.addRow(new Object[]{
                temp.getTableID(),
                temp.getTableNo(),
                temp.getFloorId(),
                temp.getChairs()
                
                
            });
        }

    }
}
